nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['https://manabu-app.vercel.app']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        expose_headers: ['Link', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://manabu-app.vercel.app']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            expose_headers: ['Link', 'Authorization']
            max_age: 3600