<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250509112746 extends AbstractMigration
{
    public function up(Schema $schema): void
{
    $this->addSql(<<<'SQL'
        CREATE TABLE exercise (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            lesson_id INT DEFAULT NULL,
            question VARCHAR(255) NOT NULL,
            options JSON NOT NULL,
            answer VARCHAR(255) NOT NULL,
            type VARCHAR(255) NOT NULL
        )
    SQL);

    $this->addSql(<<<'SQL'
        CREATE TABLE lesson (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            content TEXT NOT NULL,
            level VARCHAR(255) DEFAULT NULL,
            "order" INT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
        )
    SQL);

    $this->addSql(<<<'SQL'
        CREATE TABLE notification (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INT NOT NULL,
            message VARCHAR(255) NOT NULL,
            is_read BOOLEAN NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            type VARCHAR(50) DEFAULT NULL
        )
    SQL);

    $this->addSql(<<<'SQL'
        CREATE TABLE progression (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INT NOT NULL,
            lesson_id INT NOT NULL,
            completed BOOLEAN NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            unlocked BOOLEAN NOT NULL
        )
    SQL);

    $this->addSql(<<<'SQL'
        CREATE TABLE "user" (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(20) NOT NULL,
            email VARCHAR(255) NOT NULL,
            password VARCHAR(255) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            roles JSON NOT NULL,
            UNIQUE (username),
            UNIQUE (email)
        )
    SQL);

    // Création des index séparés (car PostgreSQL ne supporte pas INDEX dans CREATE TABLE)
    $this->addSql('CREATE INDEX IDX_AEDAD51CCDF80196 ON exercise (lesson_id)');
    $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
    $this->addSql('CREATE INDEX IDX_D5B25073A76ED395 ON progression (user_id)');
    $this->addSql('CREATE INDEX IDX_D5B25073CDF80196 ON progression (lesson_id)');

    // Contraintes de clés étrangères
    $this->addSql('ALTER TABLE exercise ADD CONSTRAINT FK_AEDAD51CCDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id)');
    $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
    $this->addSql('ALTER TABLE progression ADD CONSTRAINT FK_D5B25073A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
    $this->addSql('ALTER TABLE progression ADD CONSTRAINT FK_D5B25073CDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id)');
}

}
