<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250522120044 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE chat_message (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INT NOT NULL,
                message TEXT NOT NULL,
                is_from_user BOOLEAN NOT NULL,
                created_at TIMESTAMP NOT NULL
            )
        SQL);
    
        $this->addSql(<<<'SQL'
            CREATE TABLE game_session (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                host_id INT NOT NULL,
                guest_id INT DEFAULT NULL,
                status VARCHAR(50) NOT NULL,
                created_at TIMESTAMP NOT NULL,
                started_at TIMESTAMP DEFAULT NULL,
                ended_at TIMESTAMP DEFAULT NULL,
                host_score INT DEFAULT NULL,
                guest_score INT DEFAULT NULL,
                winner VARCHAR(50) DEFAULT NULL,
                game_data JSON DEFAULT NULL
            )
        SQL);
    
        $this->addSql(<<<'SQL'
            CREATE TABLE notification (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INT NOT NULL,
                message VARCHAR(255) NOT NULL,
                is_read BOOLEAN NOT NULL,
                created_at TIMESTAMP NOT NULL,
                type VARCHAR(50) DEFAULT NULL
            )
        SQL);
    
        // Création des index séparément
        $this->addSql('CREATE INDEX IDX_FAB3FC16A76ED395 ON chat_message (user_id)');
        $this->addSql('CREATE INDEX IDX_4586AAFB1FB8D185 ON game_session (host_id)');
        $this->addSql('CREATE INDEX IDX_4586AAFB9A4AA658 ON game_session (guest_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
    
        // Contraintes FK
        $this->addSql('ALTER TABLE chat_message ADD CONSTRAINT FK_FAB3FC16A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE game_session ADD CONSTRAINT FK_4586AAFB1FB8D185 FOREIGN KEY (host_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE game_session ADD CONSTRAINT FK_4586AAFB9A4AA658 FOREIGN KEY (guest_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
    }
    

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE chat_message DROP CONSTRAINT FK_FAB3FC16A76ED395');
        $this->addSql('ALTER TABLE game_session DROP CONSTRAINT FK_4586AAFB1FB8D185');
        $this->addSql('ALTER TABLE game_session DROP CONSTRAINT FK_4586AAFB9A4AA658');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
    
        $this->addSql('DROP TABLE chat_message');
        $this->addSql('DROP TABLE game_session');
        $this->addSql('DROP TABLE notification');
    }
    
}
