<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250522120845 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE leaderboard (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INT NOT NULL,
                total_games INT NOT NULL,
                wins INT NOT NULL,
                losses INT NOT NULL,
                draws INT NOT NULL,
                total_points INT NOT NULL,
                last_updated TIMESTAMP NOT NULL
            )
        SQL);

        $this->addSql('CREATE INDEX IDX_182E5253A76ED395 ON leaderboard (user_id)');
        $this->addSql('ALTER TABLE leaderboard ADD CONSTRAINT FK_182E5253A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE leaderboard DROP CONSTRAINT FK_182E5253A76ED395');
        $this->addSql('DROP TABLE leaderboard');
    }
}
