<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250513083700 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
        CREATE TABLE achievement (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INT DEFAULT NULL,
            title VARCHAR(255) NOT NULL,
            description TEXT NOT NULL,
            required_lessons INT NOT NULL,
            icon VARCHAR(255) NOT NULL,
            unlocked_at TIMESTAMP DEFAULT NULL
        )
    SQL);
    
    $this->addSql('CREATE INDEX IDX_96737FF1A76ED395 ON achievement (user_id)');
    
    $this->addSql(<<<'SQL'
        ALTER TABLE achievement ADD CONSTRAINT FK_96737FF1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)
    SQL);
    
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE achievement DROP CONSTRAINT FK_96737FF1A76ED395');
        $this->addSql('DROP TABLE achievement');
    }
}
