<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250522120237 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // PostgreSQL syntaxe correcte pour supprimer une contrainte FK
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT IF EXISTS FK_BF5476CAA76ED395');
        $this->addSql('DROP TABLE IF EXISTS notification');
    }
    
    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE notification (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INT NOT NULL,
                message VARCHAR(255) NOT NULL,
                is_read BOOLEAN NOT NULL,
                created_at TIMESTAMP NOT NULL,
                type VARCHAR(50) DEFAULT NULL
            )
        SQL);
    
        // Création de l'index séparément
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
    
        // Ajout de la contrainte FK
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
    }
    
}
