controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

lexik_jwt_authentication:
    resource: "@LexikJWTAuthenticationBundle/Resources/config/routing.yaml"
    prefix: /api

api_logout:
    path: /api/logout
    methods: ['POST']
api_progressions:
    path: /api/progressions