controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Route manuelle pour JWT login
api_login_check:
    path: /api/login_check
    methods: [POST]
    controller: Lexik\Bundle\JWTAuthenticationBundle\Controller\AuthenticationController::getToken

api_logout:
    path: /api/logout
    methods: ['POST']
api_progressions:
    path: /api/progressions