controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Configuration spécifique pour le login
api_login_check:
    path: /api/login_check
api_logout:
    path: /api/logout
    methods: ['POST']
api_progressions:
  path: /api/progressions
lexik_jwt_authentication_login:
    path: /login_check
    methods: [POST]
    controller: lexik_jwt_authentication.controller.authentication::getToken