FROM mysql:8.0

# Variables d'environnement par défaut (à personnaliser dans Render)
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydb
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# Port par défaut
EXPOSE 3306
