services:
  app:
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - database  

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
