services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    command: |
      bash -c "
        composer install --no-interaction --optimize-autoloader &&
        apache2-foreground
      "
