services:
  - type: web
    runtime: docker
    name: symfony-api
    plan: free
    autoDeploy: true
    branch: main
    startCommand: sh ./bin/start.sh
    dockerfilePath: ./api/Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        value: UnSuperSecret
      - key: CORS_ALLOW_ORIGIN
        value: https://examen-react.vercel.app
      - key: DATABASE_URL
        sync: false  # à configurer manuellement dans Render pour ne pas exposer le mot de passe
      - key: JWT_SECRET_KEY
        value: /var/www/api/config/jwt/private.pem
      - key: JWT_PUBLIC_KEY
        value: /var/www/api/config/jwt/public.pem
      - key: JWT_PASSPHRASE
        value: 1408
